services:
  app:
    build:
      context: .
      dockerfile: docker/back/Dockerfile.dev
    ports:
      - 2345:2345
      - 8080:8080
    volumes:
      - ./back:/app/back
    env_file:
      - .env
    environment:
      - MONGO_DATABASE=okusuri_memo

  mongo:
    image: mongo:7.0
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
