# fly.toml app configuration file generated for okusuri-memo-api on 2024-06-20T02:57:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'okusuri-memo-api'
primary_region = 'nrt'

[build]
  dockerfile = 'docker/back/Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
